name: Build and push docker image to ECR

on:
  workflow_call:
    secrets:
      nexus_host_url:
        required: true
      nexus_username:
        required: true
      nexus_password:
        required: true
      version:
        required: true
      group_id:
        required: true
      artifact_id:
        required: true
      aws_account_id:
        required: true
      env:
        required: true
      service_name:
        required: true

jobs:
  build-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven Settings XML File
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "litteranexus", "url": "${{ secrets.nexus_host_url }}", "releases": { "enabled": true }, "snapshots": { "enabled": true } }]'
          plugin_repositories: '[{ "id": "litteranexus", "url": "${{ secrets.nexus_host_url }}", "releases": { "enabled": true }, "snapshots": { "enabled": true } }]'
          servers: '[{ "id": "litteranexus", "username": "${{ secrets.nexus_username }}", "password": "${{ secrets.nexus_password }}" }]'
          active_profiles: '[ "github" ]'
          output_file: /home/runner/.m2/settings.xml

      - name: Download Artifact
        run: |
          ./mvnw dependency:copy -Dartifact=${{ secrets.GROUP_ID }}:${{ secrets.ARTIFACT_ID }}:${{ secrets.version }}:jar -DoutputDirectory=./target
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/github-assume-role

      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com
          docker build --build-arg PROFILE=${{ secrets.env }} -t ${{ secrets.service_name }} .
          docker tag ${{ secrets.service_name }}:latest ${{ secrets.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.service_name }}:${{ secrets.version }}
          docker push ${{ secrets.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.service_name }}:${{ secrets.version }}
