name: Deploy Docker image to EKS

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      environment:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      service_name:
        required: true
        type: string
      eks_config_branch:
        type: string
        required: false
        default: 'develop'
      aws_account_number:
        required: true
        type: string

    secrets:
      repo_token:
        required: true
      NEW_RELIC_LICENSE_KEY:
        required: false

env:
  image_version: ${{ inputs.image_version }}
  environment: ${{ inputs.environment }}
  cluster_name: ${{ inputs.cluster_name }}
  service_name: ${{ inputs.service_name }}
  eks_config_branch: ${{ inputs.eks_config_branch }}
  aws_account_number: ${{ inputs.aws_account_number }}


jobs:
  deploy-to-eks:
    name: Deploy docker image to EKS
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ aws_account_number }}:role/github-assume-role

      - name: Checkout EKS Config Repo
        uses: actions/checkout@v3
        with:
          repository: Littera-Education/littera-eks-config
          token: ${{ secrets.repo_token }}
          ref: ${{ inputs.eks_config_branch }}
          path: config

      - name: Deploy to EKS
        run: |
          # install kubectl
          curl -o kubectl ${{ inputs.kubctl_download_url }}
          chmod +x ./kubectl
          mkdir -p $HOME/bin && mv ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin

          # set and use kube context
          aws eks --region us-east-1 update-kubeconfig --name ${{ inputs.cluster_name }}

          # replace ECR image path in eks manifest file
          sed -i "s/${{ inputs.service_name }}:${{ inputs.environment }}/${{ inputs.service_name }}:${{ inputs.image_version }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml

          # add New Relic secret to eks manifest file
          sed -i "s/NEW_RELIC_LICENSE_KEY_VALUE/${{ secrets.NEW_RELIC_LICENSE_KEY }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml
          
          # apply manifest and deploy
          kubectl apply -f config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml
          kubectl rollout restart deployment ${{ inputs.service_name }} -n littera-services-${{ inputs.environment }}