name: Deploy Docker image to EKS

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      env:
        required: true
        type: string
      cluster_env:
        required: true
        type: string
      service_name:
        required: true
        type: string
      k8s_config_branch:
        type: string
        required: false
        default: 'develop'

    secrets:
      repo_token:
        required: true
      aws_account_id:
        required: true
      NEW_RELIC_LICENSE_KEY:
        required: false


jobs:
  deploy-to-eks:
    name: Deploy Docker image to EKS
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/github-assume-role

      - name: Checkout EKS Config Repo
        uses: actions/checkout@v2
        with:
          repository: Littera-Education/littera-eks-config
          token: ${{ secrets.repo_token }}
          ref: ${{ inputs.k8s_config_branch }}
          path: config

      - name: Deploy to EKS
        run: |
          # install kubectl
          curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.20.4/2021-04-12/bin/darwin/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && mv ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin

          # set and use kube context
          aws eks --region us-east-1 update-kubeconfig --name ${{ inputs.cluster_env }}-cluster

          # replace vars in eks manifest file
          sed -i "s/${{ inputs.service_name }}:${{ inputs.env }}/${{ inputs.service_name }}:${{ inputs.version }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.env }}-deployment.yaml
          sed -i "s/NEW_RELIC_LICENSE_KEY_VALUE/${{ secrets.NEW_RELIC_LICENSE_KEY }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.env }}-deployment.yaml
          
          # Apply manifest and deploy
          kubectl apply -f config/${{ inputs.service_name }}/eks/eks-${{ inputs.cluster_env }}-deployment.yaml
          kubectl rollout restart deployment ${{ inputs.service_name }} -n littera-services-${{ inputs.cluster_env }}