name: Deploy Docker image to EKS

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      environment:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      service_name:
        required: true
        type: string
      eks_config_branch:
        type: string
        required: false
        default: 'develop'
      aws_account_id:
        required: true
        type: string
      kubctl_download_url:
        required: true
        type: string
      iam_role:
        required: true
        type: string

    secrets:
      repo_token:
        required: true
      NEW_RELIC_LICENSE_KEY:
        required: false

jobs:
  deploy-to-eks:
    name: Deploy docker image to EKS
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github-assume-role

      - name: Checkout EKS Config Repo
        uses: actions/checkout@v3
        with:
          repository: Littera-Education/littera-eks-config
          token: ${{ secrets.repo_token }}
          ref: ${{ inputs.eks_config_branch }}
          path: config

      - name: Deploy to EKS
        run: |
          # install kubectl
          curl -o kubectl ${{ inputs.kubctl_download_url }}
          chmod +x ./kubectl
          mkdir -p $HOME/bin && mv ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH

          echo "aws version:"
          aws --version

          # set and use kube context
          aws eks --region us-east-1 update-kubeconfig --name ${{ inputs.cluster_name }}

          echo "kube version"
          kubectl version || true

          # add iam role to serviceaccount annotation
          sed -i "s|eks.amazonaws.com/role-arn:\ .*|eks.amazonaws.com/role-arn:\ ${{ inputs.iam_role }}|g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml

          # edit ECR image path in eks manifest file
          if [[ "${{ inputs.service_name }}" == "littera-core-api" ]]; then
            sed -i "s/littera-core:${{ inputs.environment }}/littera-core:${{ inputs.image_version }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml
          else
            sed -i "s/${{ inputs.service_name }}:${{ inputs.environment }}/${{ inputs.service_name }}:${{ inputs.image_version }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml
          fi

          # add New Relic secret to eks manifest file
          sed -i "s/NEW_RELIC_LICENSE_KEY_VALUE/${{ secrets.NEW_RELIC_LICENSE_KEY }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml
          
          # apply manifest and deploy
          kubectl apply -f config/${{ inputs.service_name }}/eks/eks-${{ inputs.environment }}-deployment.yaml
          if [[ "${{ inputs.service_name }}" == "littera-core-api" ]]; then
            kubectl rollout restart deployment littera-core-web -n littera-services-${{ inputs.environment }}
            kubectl rollout restart deployment littera-core-worker -n littera-services-${{ inputs.environment }}
            # github_actions_deploy_timeout
            # while [[ $status -ne 0 && $counter -lt 10 ]]
            # do 
            #   kubectl rollout status deployment ${{  inputs.service_name }} -n littera-services-${{ inputs.environment }} --timeout 5s
            #   if $status ne - 
            #     exit 1
            #   fi
            #   if [[ counter -eq 10 ]]
            #     exit 1
            #   fi

            # echo this means that $timeout has been reached
            # echo does not necessary mean that deployment was a failure
          else
            kubectl rollout restart deployment ${{ inputs.service_name }} -n littera-services-${{ inputs.environment }}
            echo "The timeout is ${{ github_actions_deploy_timeout }}...."
            kubectl rollout status deployment ${{  inputs.service_name }} -n littera-services-${{ inputs.environment }} --timeout=${{ github_actions_deploy_timeout }}
          fi