name: Deploy Docker image to EKS

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      env:
        required: true
        type: string
      cluster_env:
        required: true
        type: string
      service_name:
        required: true
        type: string
      k8s_config_branch:
        type: string
        required: false
        default: 'develop'

    secrets:
      repo_token:
        required: true
      aws_account_id:
        required: true


jobs:
  deploy-to-eks:
    name: Deploy Docker image to EKS
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/github-assume-role

      - name: Checkout EKS Config Repo
        uses: actions/checkout@v2
        with:
          repository: Littera-Education/littera-eks-config
          token: ${{ secrets.repo_token }}
          ref: ${{ inputs.k8s_config_branch }}
          path: config

      - name: Deploy to EKS
        run: |
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          aws eks --region us-east-1 update-kubeconfig --name ${{ inputs.cluster_env }}-cluster

          sed -i "s/${{ inputs.service_name }}:${{ inputs.env }}/${{ inputs.service_name }}:${{ inputs.version }}/g" config/${{ inputs.service_name }}/eks/eks-${{ inputs.env }}-deployment.yaml
          kubectl apply -f config/${{ inputs.service_name }}/eks/eks-${{ inputs.env }}-deployment.yaml
          kubectl rollout restart deployment ${{ inputs.service_name }} -n littera-services-${{ inputs.env }}