name: Maven Release

on:
  workflow_call:
    inputs:
      nexus_host_url:
        required: true
        type: string
      version:
        required: true
        type: string
      version_increment_type:
        required: true
        description: "What part of the version to increment: major, minor, or patch"
        type: string
      local_runner:
        required: false
        type: string
        default: "self-hosted-runner-standard"
      github_oidc_role:
        type: string
        default: 'not-provided'

    secrets:
      nexus_username:
        required: true
      nexus_password:
        required: true
      github_ssh_key:
        required: true

jobs:
  maven_release:
    name: Maven ${{ inputs.version_increment_type }} Release version ${{ inputs.version }}
    runs-on: ${{ inputs.local_runner }}

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Install curl, wget and unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget unzip
  
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Maven Settings XML File
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[{ "id": "litteranexus", "url": "${{ inputs.nexus_host_url }}", "releases": { "enabled": true }, "snapshots": { "enabled": true } }]'
          plugin_repositories: '[{ "id": "litteranexus", "url": "${{ inputs.nexus_host_url }}", "releases": { "enabled": true }, "snapshots": { "enabled": true } }]'
          servers: '[{ "id": "litteranexus", "username": "${{ secrets.nexus_username }}", "password": "${{ secrets.nexus_password }}" }]'
          active_profiles: '[ "github" ]'
          output_file: /home/runner/.m2/settings.xml

      - name: Get Project Info
        id: get-project-info
        run: |
          NAME=$(./mvnw -ntp help:evaluate -Dexpression=project.name -q -DforceStdout)
          echo "NAME=$NAME" >> $GITHUB_OUTPUT

      - name: Get runner arch
        if: ${{ inputs.github_oidc_role != 'not-provided' }}
        id: runner_arch
        run: |
          arch_value=$(uname -m)
          if [ "$arch_value" = "x86_64" ]; then
            echo "runner_arch=amd64" >> $GITHUB_OUTPUT
          elif [ "$arch_value" = "aarch64" ]; then
            echo "runner_arch=arm64" >> $GITHUB_OUTPUT
          fi

      - name: Setup aws cli
        if: ${{ inputs.github_oidc_role != 'not-provided' }}
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: ${{ steps.runner_arch.outputs.runner_arch }}

      - name: Configure AWS Creds
        if: ${{ inputs.github_oidc_role != 'not-provided' }}
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ inputs.github_oidc_role }}

      - name: Prep SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.github_ssh_key }}

      - name: Maven Release Patch
        if: ${{ inputs.version_increment_type == 'patch' }}
        run: |
          git config --global user.name 'Littera GitHub'
          git config --global user.email 'littera-github@litteraeducation.com'

          if [[ "${{ inputs.github_oidc_role }}" != "not-provided" ]]; then
            export DOCKER_REGISTRY_PASSWORD=$(aws ecr get-login-password --region us-east-1)
          fi

          ./mvnw -ntp --batch-mode build-helper:parse-version release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT -DreleaseVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} -Darguments='-Dmaven.test.skip=true -Dmaven.javadoc.skip=true' release:perform

      - name: Maven Release Minor
        if: ${{ inputs.version_increment_type == 'minor' }}
        run: |
          git config --global user.name 'Littera GitHub'
          git config --global user.email 'littera-github@litteraeducation.com'

          if [[ "${{ inputs.github_oidc_role }}" != "not-provided" ]]; then
            export DOCKER_REGISTRY_PASSWORD=$(aws ecr get-login-password --region us-east-1)
          fi
          
          ./mvnw -ntp --batch-mode build-helper:parse-version release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT -DreleaseVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} -Darguments='-Dmaven.test.skip=true -Dmaven.javadoc.skip=true' release:perform

      - name: Maven Release Major
        if: ${{ inputs.version_increment_type == 'major' }}
        run: |
          git config --global user.name 'Littera GitHub'
          git config --global user.email 'littera-github@litteraeducation.com'
          
          if [[ "${{ inputs.github_oidc_role }}" != "not-provided" ]]; then
            export DOCKER_REGISTRY_PASSWORD=$(aws ecr get-login-password --region us-east-1)
          fi

          ./mvnw -ntp --batch-mode build-helper:parse-version release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdevelopmentVersion=\${parsedVersion.nextMajorVersion}.0.0-SNAPSHOT -DreleaseVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} -Darguments='-Dmaven.test.skip=true -Dmaven.javadoc.skip=true' release:perform
  
      - name: Cache github pages
        id: cache-github-pages
        uses: actions/cache@v4
        with:
          path: target/docs
          key: ${{ steps.get-project-info.outputs.NAME }}-${{ inputs.version }}-github-pages

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        if: steps.cache-github-pages.outputs.cache-hit == 'true'
        continue-on-error: true
        with:
          branch: gh-pages
          target-folder: ${{ inputs.version }}
          folder: target/docs

      - name: Cache Dockerfile
        id: cache-dockerfile
        uses: actions/cache@v4
        with:
          path: Dockerfile
          key: ${{ steps.get-project-info.outputs.NAME }}-${{ inputs.version }}-dockerfile