name: NPM Build And Release

on:
  workflow_call:
    inputs:
      nexus_host_domain:
        required: true
        type: string
      artifact_id:
        required: true
        type: string
      version:
        required: true
        type: string
      node_version:
        type: string
        default: "18"
      custom_npm_install_command:
        type: string
        default: skip
      package_manager:
        type: string
        default: npm
      local_runner:
        required: false
        type: string
        default: "self-hosted-runner-standard"
      branch_name:
        required: false
        type: string

    secrets:
      nexus_username:
        required: true
      nexus_password:
        required: true
      nexus_npm_login:
        required: true
      github_actions_token:
        required: true

    outputs:
      version:
        description: "artifact version"
        value: ${{ jobs.npm_build.outputs.version }}
      artifact_url: 
        description: "artifact url"
        value: ${{ jobs.npm_build.outputs.artifact_url }}

jobs:
  npm_build:
    name: NPM Build and Release
    runs-on: ${{ inputs.local_runner }}

    outputs:
      version: ${{ steps.upload-artifact.outputs.VERSION }}
      artifact_url: ${{ steps.upload-artifact.outputs.ARTIFACT_URL }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.github_actions_token }}
          release-type: node
          target-branch: ${{ github.ref_name }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Setup .npmrc for pulling & publishing to Nexus
        run: |
          if [ "${{ inputs.package_manager }}" == "berry" ]; then
            yarn config set npmAlwaysAuth true
            yarn config set npmAuthIdent ${{ secrets.nexus_npm_login }}
            yarn config set npmRegistryServer https://${{ inputs.nexus_host_domain }}/repository/npm-public

            yarn config set 'npmRegistries["//${{ inputs.nexus_host_domain }}/repository/npm-local/"].npmAuthIdent' ${{ secrets.nexus_npm_login }}
            yarn config set 'npmRegistries["//${{ inputs.nexus_host_domain }}/repository/npm-local/"].npmAlwaysAuth' true
          elif [ "${{ inputs.package_manager }}" == "yarn" ]; then
            FULL_REPO_AUTH="_auth=${{ secrets.nexus_npm_login }}"
            echo -e "\n" \
                "registry=https://${{ inputs.nexus_host_domain }}/repository/npm-public\n" \
                "$FULL_REPO_AUTH\n" \
                "//${{ inputs.nexus_host_domain }}/repository/npm-local:_auth=${{ secrets.nexus_npm_login }}\n" \
                "email=${{ secrets.nexus_username }}\n" \
                "always-auth=true\n" \ >> .npmrc
          elif [ "${{ inputs.package_manager }}" == "npm" ]; then
              FULL_REPO_AUTH="//${{ inputs.nexus_host_domain }}/repository/:_auth=${{ secrets.nexus_npm_login }}"
              echo -e "\n" \
                "registry=https://${{ inputs.nexus_host_domain }}/repository/npm-public\n" \
                "$FULL_REPO_AUTH\n" \
                "//${{ inputs.nexus_host_domain }}/repository/npm-local:_auth=${{ secrets.nexus_npm_login }}\n" \
                "email=${{ secrets.nexus_username }}\n" \
                "always-auth=true\n" \ >> .npmrc
          fi

      - name: Install dependencies (with cache)
        if: ${{ inputs.custom_npm_install_command == 'skip' }}
        uses: bahmutov/npm-install@v1

      - name: Custom Install dependencies (with cache)
        if: ${{ inputs.custom_npm_install_command != 'skip' }}
        uses: bahmutov/npm-install@v1
        with:
          install-command: ${{ inputs.custom_npm_install_command }}

      - name: Build
        run: npm run build

      - name: Prune Dev Dependencies
        run: npm prune --production

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist node_modules package.json

      - name: Get Release PR Title
        uses: actions/github-script@v7
        id: release-pr-title
        if: inputs.branch_name != 'develop-snapshot'
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            const releasepr = prs.data.filter(pr => pr.title.includes("chore(main): release"))
            console.log(releasepr)

            if(releasepr.length > 0) {
              return releasepr.pop().title
            }

            console.log('No pending release prs found')
          result-encoding: string

      - name: upload zip file to nexus
        id: upload-artifact
        run: |
          if [ "${{ steps.release-please.outputs.release_created }}" ]; then
            version=${{ inputs.version }}
            artifact_url=https://${{ inputs.nexus_host_domain }}/repository/node-artifacts/${{ inputs.artifact_id }}/${{ inputs.version }}/dist.zip
          elif [ "${{ steps.release-pr-title.outputs.result }}" != "undefined" && inputs.branch != 'develop-snapshot']; then
            version="${{ steps.release-pr-title.outputs.result }}"
            echo $version
            versionparts=($version)
            echo ${versionparts[-1]}
            version="${versionparts[-1]}-SNAPSHOT-$(date +%Y-%m-%d-%H-%M-%S)"
            artifact_url=https://${{ inputs.nexus_host_domain }}/repository/node-artifacts/${{ inputs.artifact_id }}/$version/dist.zip
          else
            echo "WARN: Unable to get version from release-please, defaulting to package.json"
            version="$(npm pkg get version | xargs echo)-SNAPSHOT-$(date +%Y-%m-%d-%H-%M-%S)"
            artifact_url=https://${{ inputs.nexus_host_domain }}/repository/node-artifacts/${{ inputs.artifact_id }}/$version/dist.zip
          fi

          curl -v -k -u "${{secrets.nexus_username}}:${{secrets.nexus_password}}" --upload-file dist.zip $artifact_url
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "ARTIFACT_URL=$artifact_url" >> $GITHUB_OUTPUT

      - name: Cache Dockerfile
        id: cache-dockerfile
        uses: actions/cache@v4
        with:
          path: Dockerfile
          key: ${{ inputs.artifact_id }}-${{ steps.upload-artifact.outputs.VERSION }}-dockerfile
