name: NPM UI Build And Deploy

on:
  workflow_call:
    inputs:
      nexus_host_domain:
        required: true
        type: string
      artifact_id:
        required: true
        type: string
      node_version:
        type: string
        default: "18"
      package_manager:
        type: string
        default: npm
      local_runner:
        required: false
        type: string
        default: "self-hosted-runner-standard"

    secrets:
      nexus_username:
        required: true
      nexus_npm_login:
        required: true
      github_actions_token:
        required: true
      vercel_token:
        required: true
      vercel_org_id:
        required: true
      vercel_project_id:
        required: true

jobs:
  npm_build_deploy:
    name: NPM UI Build and Deploy
    runs-on: ${{ inputs.local_runner }}

    steps:
      - name: Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.github_actions_token }}
          default-branch: ${{ github.ref_name }}
          release-type: node
          package-name: ${{ inputs.artifact_id }}

  vercel_release:
    needs: [ npm_build_deploy ]
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      git_tag: ${{ github.ref_name }}
      nexus_host_domain: ${{ inputs.nexus_host_domain }}
      environment: "dev"
      node_version: ${{ inputs.node_version }}
      package_manager: ${{ inputs.package_manager }}
      local_runner: ${{ inputs.local_runner }}
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_npm_login: ${{ secrets.NEXUS_NPM_LOGIN }}
      vercel_token: ${{ secrets.vercel_token }}
      vercel_org_id: ${{ secrets.vercel_org_id }}
      vercel_project_id: ${{ secrets.vercel_project_id }}
      github_actions_token: ${{ secrets.github_actions_token }}