name: PR Title Lint

on:
  workflow_call:
    inputs:
      nexus_host_domain:
        required: true
        type: string
      node_version:
        type: number
        default: 16

    secrets:
      nexus_username:
        required: true
      nexus_npm_login:
        required: true

jobs:
  pr_title_lint:
    name: PR Title Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Setup .npmrc for pulling & publishing to Nexus
        run: |
          echo -e '\n' \
          'registry=https://${{ inputs.nexus_host_domain }}/repository/npm-public\n' \
          '_auth=${{ secrets.nexus_npm_login }}\n' \
          '//${{ inputs.nexus_host_domain }}/repository/npm-local:_auth=${{ secrets.nexus_npm_login }}\n' \
          'email=${{ secrets.nexus_username }}\n' \
          'always-auth=true\n' \
          >> .npmrc
          
      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint PR Title
        uses: JulienKode/pull-request-name-linter-action@v0.5.0