name: PR Title Lint

on:
  workflow_call:
    inputs:
      nexus_host_domain:
        required: true
        type: string
      node_version:
        type: string
        default: 18
      package_manager:
        type: string
        default: npm
      local_runner:
        required: false
        type: string
        default: "self-hosted-runner-standard"

    secrets:
      nexus_username:
        required: true
      nexus_npm_login:
        required: true

jobs:
  pr_title_lint:
    name: PR Title Lint
    runs-on: ${{ inputs.local_runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Setup .npmrc for pulling & publishing to Nexus
        run: |
          if [ "${{ inputs.package_manager }}" == "berry" ]; then
            yarn config set npmAlwaysAuth true
            yarn config set npmAuthIdent ${{ secrets.nexus_npm_login }}
            yarn config set npmRegistryServer https://${{ inputs.nexus_host_domain }}/repository/npm-public

            yarn config set 'npmRegistries["//${{ inputs.nexus_host_domain }}/repository/npm-local/"].npmAuthIdent' ${{ secrets.nexus_npm_login }}
            yarn config set 'npmRegistries["//${{ inputs.nexus_host_domain }}/repository/npm-local/"].npmAlwaysAuth' true
          elif [ "${{ inputs.package_manager }}" == "yarn" ]; then
            FULL_REPO_AUTH="_auth=${{ secrets.nexus_npm_login }}"
            echo -e "\n" \
                "registry=https://${{ inputs.nexus_host_domain }}/repository/npm-public\n" \
                "$FULL_REPO_AUTH\n" \
                "//${{ inputs.nexus_host_domain }}/repository/npm-local:_auth=${{ secrets.nexus_npm_login }}\n" \
                "email=${{ secrets.nexus_username }}\n" \
                "always-auth=true\n" \ >> .npmrc
          elif [ "${{ inputs.package_manager }}" == "npm" ]; then
              FULL_REPO_AUTH="//${{ inputs.nexus_host_domain }}/repository/:_auth=${{ secrets.nexus_npm_login }}"
              echo -e "\n" \
                "registry=https://${{ inputs.nexus_host_domain }}/repository/npm-public\n" \
                "$FULL_REPO_AUTH\n" \
                "//${{ inputs.nexus_host_domain }}/repository/npm-local:_auth=${{ secrets.nexus_npm_login }}\n" \
                "email=${{ secrets.nexus_username }}\n" \
                "always-auth=true\n" \ >> .npmrc
          fi

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Set Up Config file
        run: |
          if [ ! -f commitlint.config.js ]; then
            echo "
            module.exports = {
              extends: [\"@commitlint/config-conventional\"],
              ignores: [(message) => /^Bumps \[.+]\(.+\) from .+ to .+\.$/m.test(message)],
              rules: { 'subject-case': [0,'always',['sentence-case']],'header-max-length': [2, 'always', 120], 'body-max-line-length': [0, 'always', 120] },
            }" >> commitlint.config.js
          fi
      
      - name: Set up dependency
        run: |
          if [ ! -d node_modules/@commitlint ]; then
            npm i @commitlint/config-conventional
          fi

      - name: Lint PR Title
        run: |
          echo "${PR_TITLE}" | npx --yes commitlint
        env:
          PR_TITLE: '${{ github.event.pull_request.title }}'