name: Turborepo - Find Pending Apps

on:
  workflow_call:
    inputs:
      nexus_host_domain:
        required: true
        type: string
      node_version:
        type: string
        default: 18
      local_runner:
        required: false
        type: string
        default: "self-hosted-runner-standard"
      all_apps:
        required: true
        type: string

    secrets:
      nexus_username:
        required: true
      nexus_npm_login:
        required: true

    outputs:
      pending_apps:
        description: list of all apps in the repository with pending changes
        value: ${{ jobs.turbo-find-pending-apps.outputs.pending_apps }}
      length:
        description: length of the list of apps with pending changes
        value: ${{ jobs.turbo-find-pending-apps.outputs.length }}

jobs:
  turbo-find-pending-apps:
    name: Turbo Find Pending Apps
    runs-on: ${{ inputs.local_runner }}

    outputs:
      pending_apps: ${{ steps.turbo_find_pending_apps.outputs.pending_apps }}
      length: ${{ steps.turbo_find_pending_apps.outputs.length }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Setup .npmrc for pulling & publishing to Nexus
        run: |
          FULL_REPO_AUTH="//${{ inputs.nexus_host_domain }}/repository/:_auth=${{ secrets.nexus_npm_login }}"
          echo -e "\n" \
            "registry=https://${{ inputs.nexus_host_domain }}/repository/npm-public\n" \
            "$FULL_REPO_AUTH\n" \
            "//${{ inputs.nexus_host_domain }}/repository/npm-local:_auth=${{ secrets.nexus_npm_login }}\n" \
            "email=${{ secrets.nexus_username }}\n" \
            "always-auth=true\n" \ >> .npmrc

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Find Pending Turborepo Apps
        id: turbo_find_pending_apps
        # https://github.com/orgs/community/discussions/46992
        run: |
          set +e
          pending_apps=""
          for app in ${{ join(fromJSON(inputs.all_apps), ' ') }}
          do
            npx turbo-ignore $app --task=build
            if [ $? -ne 0 ]; then
              pending_apps+="\"$app\","
            fi
          done
          pending_apps="[${pending_apps%?}]"
          echo "pending_apps="$pending_apps
          echo "length=$(echo $pending_apps | jq length)"
          echo "pending_apps="$pending_apps >> $GITHUB_OUTPUT
          echo "length=$(echo $pending_apps | jq length)" >> $GITHUB_OUTPUT